config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path("select2/", include("django_select2.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path
from core.erp.views.dashboard.views import *
from core.erp.views.estudiantes.views import *
from core.erp.views.profesores.views import *
from core.erp.views.niveles.views import *
from core.erp.views.pagos.views import *




app_name = 'erp'

urlpatterns = [
    path('estudiantes/list/',EstudiantesListView.as_view(), name='estudiante_list'),
    path('estudiantes/add/', EstudiantesCreateView.as_view(), name='estudiante_create'),
    path('estudiantes/update/<int:pk>/', EstudiantesUpdateView.as_view(), name='estudiante_update'),
    path('estudiantes/delete/<int:pk>/', EstudiantesDeleteView.as_view(), name='estudiante_delete'),
     # Docentes
    path('profesores/list/', ProfesoresListView.as_view(), name='profesores_list'),
    path('profesores/add/', ProfesoresCreateView.as_view(), name='profesores_create'),
    path('profesores/update/<int:pk>/', ProfesoresUpdateView.as_view(), name='profesores_update'),
    path('profesores/delete/<int:pk>/', ProfesoresDeleteView.as_view(), name='profesores_delete'),
    
     # Niveles
    path('niveles/list/', NivelesListView.as_view(), name='niveles_list'),
    path('niveles/add/', NivelesCreateView.as_view(), name='niveles_create'),
    path('niveles/update/<int:pk>/', NivelesUpdateView.as_view(), name='niveles_update'),
    path('niveles/delete/<int:pk>/', NivelesDeleteView.as_view(), name='niveles_delete'),
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # home
    path('pagoslist/', PagosListView.as_view(), name='pagos_list'),
    path('pagos/create/', PagosCreateView.as_view(), name='pagos_create'),
    path('pagos/update/<int:pk>/', PagosUpdateView.as_view(), name='pagos_update'),
    path('pagos/delete/<int:pk>/', PagosDeleteView.as_view(), name='pagos_delete'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed custom-body">
    <div class="wrapper custom-wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper custom-content-wrapper">
            <div class="content-header custom-content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">  <small class="custom-small">Novus Lingua System</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right custom-breadcrumb">
                                <li class="breadcrumb-item"><a href="#" class="custom-breadcrumb-link">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}" class="custom-breadcrumb-link">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content custom-content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link" style="color: #08d9d6;">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#" style="color: #08d9d6;">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="background-color: #252a34;">
                    <span class="dropdown-header" style="color: #08d9d6;">
                        Último Acceso: 12 de Abril de 2020
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item" style="color: #08d9d6;">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item" style="color: #08d9d6;">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer" style="color: #08d9d6;">
                    <p>Este sistema te permitirá realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" style="color: #08d9d6;">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link" style="color: #08d9d6; border: 2px solid #08d9d6;">
        <img src="{% static 'img/min1.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
             <span class="brand-text font-weight-light" style="color: #08d9d6;">Novus Lingua</span>
            </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="border-bottom: 2px solid #08d9d6;">
            <div class="image">
                <img src="{% static 'img/user.png' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block" style="color: #08d9d6;">Usuario</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header" style="color: #08d9d6;">Menú</li>
                <li class="nav-item">
                    <a href="{% url 'erp:estudiante_list' %}" class="nav-link" style="color: #08d9d6;">
                        <i class="fa-solid fa-users"></i>
                        <p>
                            Estudiantes
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:pagos_list' %}" class="nav-link" style="color: #08d9d6;">
                        <i class="fa-solid fa-cash-register"></i>
                        <p>
                            Pagos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:niveles_list' %}" class="nav-link" style="color: #08d9d6;">
                        <i class="fa-solid fa-book-open-reader"></i>
                        <p>
                            Niveles
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:profesores_list' %}" class="nav-link" style="color: #08d9d6;">
                        <i class="fa-solid fa-chalkboard-user"></i>
                        <p>
                            Profesores
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>